export const COUNTRIES = [
    "Venezuela", "Colombia", "Argentina", "Chile", "Perú", "Ecuador", "Bolivia", "Paraguay", "Uruguay", "Brasil",
    "México", "España", "Estados Unidos", "Canadá", "Afganistán", "Albania", "Alemania", "Andorra", "Angola",
    "Antigua y Barbuda", "Arabia Saudita", "Argelia", "Armenia", "Australia", "Austria", "Azerbaiyán", "Bahamas",
    "Bangladés", "Barbados", "Bélgica", "Belice", "Benín", "Bielorrusia", "Bosnia y Herzegovina", "Botsuana",
    "Brasil", "Bulgaria", "Burkina Faso", "Burundi", "Bután", "Cabo Verde", "Camboya", "Camerún", "Chad",
    "China", "Chipre", "Comoras", "Congo", "Corea del Norte", "Corea del Sur", "Costa de Marfil", "Costa Rica",
    "Croacia", "Cuba", "Dinamarca", "Dominica", "Egipto", "El Salvador", "Emiratos Árabes Unidos", "Eritrea",
    "Eslovaquia", "Eslovenia", "Estonia", "Etiopía", "Filipinas", "Finlandia", "Fiyi", "Francia", "Gabón",
    "Gambia", "Georgia", "Ghana", "Granada", "Grecia", "Guatemala", "Guinea", "Guinea-Bisáu", "Guinea Ecuatorial",
    "Guyana", "Haití", "Honduras", "Hungría", "India", "Indonesia", "Irak", "Irán", "Irlanda", "Islandia",
    "Israel", "Italia", "Jamaica", "Japón", "Jordania", "Kazajistán", "Kenia", "Kirguistán", "Kiribati",
    "Kuwait", "Laos", "Lesoto", "Letonia", "Líbano", "Liberia", "Libia", "Liechtenstein", "Lituania",
    "Luxemburgo", "Macedonia del Norte", "Madagascar", "Malasia", "Malaui", "Maldivas", "Malí", "Malta",
    "Marruecos", "Mauricio", "Mauritania", "Micronesia", "Moldavia", "Mónaco", "Mongolia", "Montenegro",
    "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Nicaragua", "Níger", "Nigeria", "Noruega",
    "Nueva Zelanda", "Omán", "Países Bajos", "Pakistán", "Palaos", "Panamá", "Papúa Nueva Guinea", "Polonia",
    "Portugal", "Qatar", "Reino Unido", "República Centroafricana", "República Checa", "República Dominicana",
    "Ruanda", "Rumanía", "Rusia", "Samoa", "San Cristóbal y Nieves", "San Marino", "San Vicente y las Granadinas",
    "Santa Lucía", "Santo Tomé y Príncipe", "Senegal", "Serbia", "Seychelles", "Sierra Leona", "Singapur",
    "Siria", "Somalia", "Sri Lanka", "Suazilandia", "Sudáfrica", "Sudán", "Suecia", "Suiza", "Surinam",
    "Tailandia", "Tanzania", "Tayikistán", "Timor Oriental", "Togo", "Tonga", "Trinidad y Tobago", "Túnez",
    "Turkmenistán", "Turquía", "Tuvalu", "Ucrania", "Uganda", "Uzbekistán", "Vanuatu", "Vietnam", "Yemen",
    "Yibuti", "Zambia", "Zimbabue"
].sort();

export const NATIONALITIES = [
    "Venezolano/a", "Colombiano/a", "Argentino/a", "Chileno/a", "Peruano/a", "Ecuatoriano/a", "Boliviano/a",
    "Paraguayo/a", "Uruguayo/a", "Brasileño/a", "Mexicano/a", "Español/a", "Estadounidense", "Canadiense",
    "Afgano/a", "Albanés/a", "Alemán/a", "Andorrano/a", "Angoleño/a", "Argelino/a", "Armenio/a", "Australiano/a",
    "Austríaco/a", "Belga", "Beliceño/a", "Bielorruso/a", "Británico/a", "Búlgaro/a", "Camerunés/a", "Chino/a",
    "Coreano/a", "Costarricense", "Cubano/a", "Danés/a", "Dominicano/a", "Egipcio/a", "Salvadoreño/a", "Francés/a",
    "Griego/a", "Guatemalteco/a", "Haitiano/a", "Hondureño/a", "Indio/a", "Indonesio/a", "Iraquí", "Iraní",
    "Irlandés/a", "Israelí", "Italiano/a", "Japonés/a", "Libanés/a", "Marroquí", "Nicaragüense", "Noruego/a",
    "Panameño/a", "Polaco/a", "Portugués/a", "Ruso/a", "Sirio/a", "Sudafricano/a", "Sueco/a", "Suizo/a",
    "Tailandés/a", "Turco/a", "Ucraniano/a", "Vietnamita"
].sort();

export const SPECIALTIES = [
    "OBRERO DE 1era.", "VIGILANTE", "AYUDANTE", "AUXILIAR DE DEPOSITO", "CHOFER DE 4ta.",
    "OPERADOR DE MARTILLO PERFORADOR", "AYUDANTE DE OPERADORES", "AYUDANTE DE MECANICO DIESEL",
    "AYUDANTE DE TOPOGRAFO", "RASTRILLERO", "ESPESORISTA", "PALERO ASFALTICO", "CAPORAL",
    "ALBAÑIL DE 2da.", "CARPINTERO DE 2da.", "CABILLERO DE 2da.", "PLOMERO DE 2da.",
    "ELECTRICISTA DE 2da.", "GRANITERO DE 2da.", "PINTOR DE 2da.", "IMPERMEABILIZADOR DE 2da.",
    "GÜINCHERO", "MAQUINISTA DE CONCRETO DE 2da.", "OPERADOR DE PLANTA FIJA DE 2da.",
    "CHOFER DE 3ra. (HASTA 3 TONS)", "OPERADOR DE EQUIPO PERFORADOR", "OPERADOR DE EQUIPO LIVIANO",
    "ENGRASADOR", "CAUCHERO", "MECÁNICO DE GASOLINA DE 2da.", "SOLDADOR DE 3ra.",
    "LATONERO DE 2da.", "INSTALADOR ELECTRICOMECANICO DE 2da.", "OPERADOR EQUIPO DE SANDBLASTING",
    "MAQUINISTA DE CONCRETO de 1ra.", "OPERADOR DE PLANTA FIJA DE 1ra.", "CHOFER DE 2da. (DE 3 A 8 TONS)",
    "OPERADOR DE PALA HASTA 1YARDA CUB.", "MECANICO DE GASOLINA DE 1ra.", "SOLDADOR DE 2da.",
    "OPERADOR DE PAVIMENTADORA", "ALBAÑIL DE 1ra.", "CARPINTERO DE 1ra.", "CABILLERO DE 1ra.",
    "PLOMERO DE 1ra.", "ELECTRICISTA DE 1ra.", "GRANITERO DE 1ra.", "PINTOR DE 1ra.",
    "IMPERMEABILIZADOR DE 1ra.", "CHOFER DE 1ra. (DE 8 A 15 TONS)", "OPERADOR DE EQUIPO PESADO DE 2da.",
    "TRACTORISTA DE 2da.", "OPERADOR DE MOTOTRAILLA DE 2da.", "OPERADOR DE MOTONIVELADORA DE 2da.",
    "OPERADOR DE GRUA (GRUERO) DE 2da.", "MECANICO EQUIPO PESADO DE 2da.", "OPERADOR MAQUINAS-HERRAMIENTAS 2da.",
    "SOLDADOR DE 1ra.", "TUBERO FABRICADOR", "MONTADOR", "LATONERO DE 1ra.",
    "INSTALADOR ELECTRICOMECANICO DE 1ra.", "LINIERO DE 1ra.", "ALBAÑIL REFRACTARIO",
    "DEPOSITARIO", "DUCTERO", "ARMADOR METALICO", "MAESTRO CARPINTERO DE 2da.",
    "CHOFER DE CAMIÓN MAS DE 15 TONS.", "CHOFER DE GANDOLA DE 2da. (DE 15-40T)",
    "CHOFER DE CAMIÓN MEZCLADOR", "OPERADOR DE PALA MAS 1YARDA CUB. DE 2da.", "PROYECTADOR DE CONCRETO",
    "CHOFER DE VOLTEO DE 30 O MAS TONELADAS", "MAESTRO ALBAÑIL", "MAESTRO CARPINTERO DE 1ra.",
    "MAESTRO CABILLERO", "MAESTRO PLOMERO DE 1ra.", "MAESTRO ELECTRICISTA", "MAESTRO GRANITERO",
    "MAESTRO PINTOR", "MAESTRO IMPERMEABILIZADOR", "MAESTRO DE OBRA DE 2da.",
    "CHOFER DE GANDOLA DE 1ra. (TODO TON.)", "DINAMITERO", "CAPORAL DE EQUIPO",
    "MAESTRO DE OBRAS ELECTROMECANICAS", "ALINEADOR DE GRUA (REGGE)", "MINERO", "MAESTRO DE VOLADURAS",
    "OPERADOR DE EQUIPO PESADO de 1ra.", "TRACTORISTA DE 1ra.", "OPERADOR DE MOTOTRAILLA DE 1ra.",
    "OPERADOR DE PALA MAS 1YARDA CUB. DE 1ra.", "OPERADOR DE MOTONIVELADORA DE 1ra.",
    "OPERADOR DE GRÚA (GRUERO) DE 1ra.", "MECÁNICO EQUIPO PESADO DE 1ra.", "OPERADOR MÁQUINAS-HERRAMIENTAS 1ra.",
    "OPERADOR DE PLANTA", "OPERADOR DE ALIVA", "MAESTRO DE OBRA de 1ra.", "MAESTRO MECÁNICO"
];

